language: c
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y check gcc-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo pip install cpp-coveralls
script:
  - autoreconf -i && ./configure ${FEATURES} --enable-gcov CFLAGS="-g -O0" && make && make check
after_success:
  - coveralls --gcov gcov-4.9 --exclude check --gcov-options '\-lp' -b .
after_failure:
  - cat $(find check -iname '*.log') /dev/null

env:
  matrix:
    - FEATURES=""
    - FEATURES="--with-fixed-allocator"
